fix: sjekk image tag semver i promote app også
Signed-off-by: anderssonw <wandersson.98@gmail.com>

diff --git a/.github/workflows/promote-app.yaml b/.github/workflows/promote-app.yaml
--- a/.github/workflows/promote-app.yaml
+++ b/.github/workflows/promote-app.yaml
@@ -23,6 +23,11 @@ on:
         description: "The cluster to promote to"
         required: true
         type: string
+      allow_unsafe_deploy:
+        description: "Whether or not applications can be deployed with image tags that are considered unsafe"
+        type: boolean
+        default: false
+        required: false
 
 permissions:
   id-token: write
@@ -52,6 +57,18 @@ jobs:
 
           FROM_APPLICATION="${{ inputs.cluster_from }}/${{ inputs.namespace_from }}/${{ inputs.application_name }}"
           TO_APPLICATION="${{ inputs.cluster_to }}/${{ inputs.namespace_to }}/${{ inputs.application_name }}"
+
+          IMAGE_TAG="$(cat "${FROM_APPLICATION}-version")"
+
+          if [ "${{ inputs.allow_unsafe_deploy }}" = "false" ]; then
+
+              # Check if image_tag matches the semantic version pattern
+              # The pattern is a simplified version which allows any -suffix, even if non-standard
+              if ! [[ "$IMAGE_TAG" =~ ^v(\d|[1-9]\d+)\.(\d|[1-9]\d+)\.(\d|[1-9]\d+)(-\S+)?$ ]]; then
+                  echo "Error: image_tag '$IMAGE_TAG' does not match required version format v#.#.#[-suffix]"
+                  exit 1
+              fi
+          fi
 
           cp env/"$FROM_APPLICATION"-version env/"$TO_APPLICATION"-version
 
