sjekk hele image versjon fremfor kun tag
Signed-off-by: anderssonw <wandersson.98@gmail.com>

diff --git a/.github/workflows/promote-app.yaml b/.github/workflows/promote-app.yaml
--- a/.github/workflows/promote-app.yaml
+++ b/.github/workflows/promote-app.yaml
@@ -58,14 +58,14 @@ jobs:
           FROM_APPLICATION="${{ inputs.cluster_from }}/${{ inputs.namespace_from }}/${{ inputs.application_name }}"
           TO_APPLICATION="${{ inputs.cluster_to }}/${{ inputs.namespace_to }}/${{ inputs.application_name }}"
 
-          IMAGE_TAG="$(cat "env/${FROM_APPLICATION}-version")"
+          IMAGE_VERSION="$(cat "env/${FROM_APPLICATION}-version")"
 
           if [ "${{ inputs.allow_unsafe_deploy }}" = "false" ]; then
 
-              # Check if image_tag matches the semantic version pattern
+              # Check if image version contains a semantic version pattern
               # The pattern is a simplified version which allows any -suffix, even if non-standard
-              if ! [[ "$IMAGE_TAG" =~ ^v(\d|[1-9]\d+)\.(\d|[1-9]\d+)\.(\d|[1-9]\d+)(-\S+)?$ ]]; then
-                  echo "Error: image_tag ${IMAGE_TAG} does not match required version format v#.#.#[-suffix]"
+              if ! [[ "$IMAGE_VERSION" =~ ^.+:v(\d|[1-9]\d+)\.(\d|[1-9]\d+)\.(\d|[1-9]\d+)(-\S+)?@.+$ ]]; then
+                  echo "Error: Image version ${IMAGE_VERSION} does not contain required version format v#.#.#[-suffix]"
                   exit 1
               fi
           fi
