Tilpasser validering og parsing for å støtte ulike versjonsnummer
* Justerer validering til å tillate versjonsnummer som starter med tall og potensielt en `v` for å støtte versjonsnummer på formatet `2026.01.01-10.00-7h638` og på v0.0.0.
* Tilpasser uthenting av versjonsnummer ved promotering fra miljø til å støtte både versjonsnummer på formatet v0.0.0 og nytt datobasert versjonsnummer

diff --git a/.github/workflows/promote-app.yaml b/.github/workflows/promote-app.yaml
--- a/.github/workflows/promote-app.yaml
+++ b/.github/workflows/promote-app.yaml
@@ -63,14 +63,13 @@ jobs:
           TO_APPLICATION="${{ inputs.cluster_to }}/${{ inputs.namespace_to }}/${{ inputs.application_name }}/${{ inputs.application_name }}"
 
           IMAGE_VERSION="$(cat "env/${FROM_APPLICATION}-version")"
-          IMAGE_TAG="$(echo $IMAGE_VERSION | sed 's/.*:\(v[^@]*\).*/\1/')"
+          IMAGE_TAG="$(echo $IMAGE_VERSION | sed -E 's/.*:([^@]*)@.*/\1/')"
 
           if [ "${{ inputs.allow_unsafe_deploy }}" = "false" ]; then
 
-              # Check if image version contains a semantic version pattern
-              # The pattern is a simplified version which allows any -suffix, even if non-standard
-              if ! [[ "$IMAGE_VERSION" =~ ^.+:v([0-9]|[1-9][0-9]+)\.([0-9]|[1-9][0-9]+)\.([0-9]|[1-9][0-9]+)(-\S+)?@.+$ ]]; then
-                  echo "Error: Image version ${IMAGE_VERSION} does not contain required version format v#.#.#[-suffix]"
+              # Check if image version starts with a number or a v and a number to support official numbers built from main branch
+              if ! [[ "$IMAGE_TAG" =~ ^v?[0-9] ]]; then
+                  echo "Error: Image version ${IMAGE_VERSION} does not contain required version format"
                   exit 1
               fi
           fi
