Revert "Tilpass krav til versjonsnummer for å støtte nytt versjonsregime i alle workflows"
This reverts commit fbe17ecd47013921b252e75e5b01fd73a6c79473.

diff --git a/.github/workflows/update-app-version.yaml b/.github/workflows/update-app-version.yaml
--- a/.github/workflows/update-app-version.yaml
+++ b/.github/workflows/update-app-version.yaml
@@ -71,9 +71,10 @@ jobs:
 
           if [ "${{ inputs.allow_unsafe_deploy }}" = "false" ]; then
 
-              # Check if image version starts with a number or a v and a number to support official numbers built from main branch
-              if ! [[ "$IMAGE_VERSION" =~ ^v?[0-9] ]]; then
-                  echo "Error: Image version ${IMAGE_VERSION} does not contain required version format"
+              # Check if image_tag matches the semantic version pattern
+              # The pattern is a simplified version which allows any -suffix, even if non-standard
+              if ! [[ "$IMAGE_TAG" =~ ^v([0-9]|[1-9][0-9]+)\.([0-9]|[1-9][0-9]+)\.([0-9]|[1-9][0-9]+)(-\S+)?$ ]]; then
+                  echo "Error: Image tag $IMAGE_TAG does not match required version format v#.#.#[-suffix]"
                   exit 1
               fi
           fi
